echo Installing...
echo Making directories...
sudo mkdir /usr/share/boiler/
sudo mkdir /usr/share/boiler/template/
echo Copying templates...
sudo cp boilerplates/* /usr/share/boiler/template/
echo Compiling...
g++ -o boiler src/generate.cpp src/main.cpp
echo Copying binary...
sudo cp boiler /usr/bin/
echo Copying uninstaller...
sudo cp uninstall.sh /usr/share/boiler/
echo Cleaning up...
rm boiler
echo Done.
echo To uninstall the app, run uninstall.sh.